load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "bzl_lib",
    srcs = [
        "download.bzl",
        "glsl.bzl",
        "hlsl.bzl",
        "resolve.bzl",
        "shader_group.bzl",
        "slang.bzl",
        "spirv_cross.bzl",
        "versions.bzl",
    ],
    visibility = ["//visibility:public"],
)
