load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "bzl_lib",
    srcs = [
        "download.bzl",
        "resolve.bzl",
        "versions.bzl",
    ],
    visibility = ["//visibility:public"],
)
