"""Common utilities for shader rules."""

def resolve_includes(ctx):
    """Resolves include search paths from hdrs and includes attributes.

    Args:
        ctx: Rule context. The rule must define hdrs (label_list) and includes (string_list) attributes.

    Returns:
        A list of include directory paths.
    """
    dirs = {}

    # Derive -I paths from the directories of header files. Since Bazel resolves label targets in hdrs to actual
    # file paths, hdr.dirname gives us the correct directory relative to the exec root. This handles the common
    # case where shaders include headers by filename (e.g. #include "common.h").
    for hdr in ctx.files.hdrs:
        dirs[hdr.dirname] = True

    # Resolve explicit include paths relative to the package. Each entry produces two paths:
    #   1. Source tree path (e.g. "foo/bar/shaders") — for headers checked into the repository.
    #   2. Bin directory path (e.g. "bazel-out/.../bin/foo/bar/shaders") — for headers generated by other rules
    #      (e.g. genrule), which are placed under the output directory rather than the source tree.
    # This follows the same convention as cc_library's includes attribute in rules_cc.
    for path in ctx.attr.includes:
        pkg = ctx.label.package
        if pkg:
            pkg_path = "{}/{}".format(pkg, path) if path else pkg
        else:
            pkg_path = path if path else "."
        dirs[pkg_path] = True
        dirs["{}/{}".format(ctx.bin_dir.path, pkg_path)] = True

    return dirs.keys()
