load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "bzl_lib",
    srcs = [
        "rules.bzl",
        "toolchain.bzl",
    ],
    visibility = ["//docs:__subpackages__"],
)
