name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildifier:
    name: Buildifier
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: bazelisk run :lint

  docs:
    name: Verify Docs
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - run: bazelisk run //docs:update_test

  tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        bazel: [7.6.1, 8.2.1]

    steps:
      - uses: actions/checkout@v2
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - run: bazelisk test //vulkan/tests/...
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}

  e2e:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: |
          # Build test app
          bazelisk run :app --verbose_failures
          # Compilers must be callable directly
          bazelisk run "@vulkan_sdk_1.4.313//:dxc" -- -help
          bazelisk run "@vulkan_sdk_1.4.313//:slangc" -- -help

        working-directory: e2e/smoke

