name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildifier:
    name: Buildifier
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5
      - run: go install github.com/bazelbuild/buildtools/buildifier@latest
      - run: buildifier -mode check -lint=warn -r .

