name: Publish to BCR
on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      publish_token:
        required: true

  workflow_dispatch:
    inputs:
      tag_name:
        description: Git tag being released
        required: true
        type: string

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.1.0
    with:
      tag_name: ${{ inputs.tag_name }}
      registry_fork: mxpv/bazel-central-registry
    permissions:
      attestations: write
      contents: write
      id-token: write
    secrets:
      publish_token: ${{ secrets.publish_token || secrets.BCR_PUBLISH_TOKEN }}

