name: Release
on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      publish_token:
        required: true

  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.2
    with:
      release_files: rules_vulkan-*.tar.gz
      prerelease: false
      tag_name: ${{ github.ref_name }}

  publish:
    needs: release
    uses: ./.github/workflows/publish.yml
    with:
      tag_name: ${{ github.ref_name }}
    secrets:
      publish_token: ${{ secrets.publish_token || secrets.BCR_PUBLISH_TOKEN }}

